src/Domain/Infra/Bundle/ServiceConfigHelper.php
src/User/Infra/Security/NativeBcryptPasswordEncoder.php
src/User/Infra/Security/SecurityUserProvider.php
src/User/Infra/Twig/UserExtension.php
src/User/Tests/Infra/Security/NativeBcryptPasswordEncoderTest.php

along with https://github.com/msgphp/user-bundle/pull/3
cc @GawainLynch

Fixes for a fresh install of msgphp/user-bundle

---

.gitignore
.travis.yml
.travis/composer.json

- Use the .travis directory as a project
- Update gitignore
- Add to Travis builds

Implement PHP-CS-Fixer as a CI component

---

.php_cs.dist
src/Domain/Tests/Entity/ChainEntityFactoryTest.php
src/Eav/Tests/Entity/AttributeTest.php
src/Eav/Tests/Entity/AttributeValueTest.php
src/Eav/Tests/Entity/Fields/AttributeValueFieldTest.php
src/User/Tests/Entity/Fields/UserFieldTest.php
src/User/Tests/Entity/UserAttributeValueTest.php
src/User/Tests/Entity/UserRoleTest.php
src/User/Tests/Entity/UserSecondaryEmailTest.php
src/User/Tests/Entity/UserTest.php
src/User/Tests/Infra/Security/SecurityUserFactoryTest.php
src/User/Tests/Infra/Security/SecurityUserProviderTest.php
src/User/Tests/Infra/Security/SecurityUserTest.php

Keeping things simple. :smile: 
FYI I'm breaking this out of the PHPStan branch to keep that one focused.

Refactor test mocking

---

bin/clean
bin/composer
bin/phpunit

Add output to commands to indicate target directory

---

bin/phpunit
src/Domain/DomainCollectionInterface.php
src/Domain/Infra/Doctrine/DomainCollection.php
src/Domain/Infra/Doctrine/DomainEntityRepositoryTrait.php
src/Domain/Infra/InMemory/DomainCollection.php
src/Domain/Infra/InMemory/DomainEntityRepositoryTrait.php
src/Domain/Tests/Infra/Doctrine/DomainEntityCollectionTest.php
src/Domain/Tests/Infra/Doctrine/DomainEntityRepositoryTraitTest.php
src/Domain/Tests/Infra/InMemory/DomainEntityCollectionTest.php
src/Domain/Tests/Infra/InMemory/DomainEntityRepositoryTraitTest.php
src/Eav/Infra/Doctrine/Repository/AttributeRepository.php
src/Eav/Infra/InMemory/Repository/AttributeRepository.php
src/Eav/Repository/AttributeRepositoryInterface.php
src/User/Infra/Doctrine/Repository/PendingUserRepository.php
src/User/Infra/Doctrine/Repository/UserAttributeValueRepository.php
src/User/Infra/Doctrine/Repository/UserRepository.php
src/User/Infra/Doctrine/Repository/UserRoleRepository.php
src/User/Infra/Doctrine/Repository/UserSecondaryEmailRepository.php
src/User/Infra/InMemory/Repository/PendingUserRepository.php
src/User/Infra/InMemory/Repository/UserAttributeValueRepository.php
src/User/Infra/InMemory/Repository/UserRepository.php
src/User/Infra/InMemory/Repository/UserRoleRepository.php
src/User/Infra/InMemory/Repository/UserSecondaryEmailRepository.php
src/User/Repository/PendingUserRepositoryInterface.php
src/User/Repository/UserAttributeValueRepositoryInterface.php
src/User/Repository/UserRepositoryInterface.php
src/User/Repository/UserRoleRepositoryInterface.php
src/User/Repository/UserSecondaryEmailRepositoryInterface.php

split from #25 and to go first

revise domain collection offset/limit api

---

src/User/Entity/PendingUser.php
src/User/Entity/User.php
src/User/Entity/UserAttributeValue.php
src/User/Entity/UserRole.php
src/User/Entity/UserSecondaryEmail.php
src/User/Infra/Doctrine/Resources/mapping-eav/UserAttributeValue.orm.xml
src/User/Infra/Doctrine/Resources/mapping/PendingUser.orm.xml
src/User/Infra/Doctrine/Resources/mapping/User.orm.xml
src/User/Infra/Doctrine/Resources/mapping/UserRole.orm.xml
src/User/Infra/Doctrine/Resources/mapping/UserSecondaryEmail.orm.xml
src/User/Tests/Entity/PendingUserTest.php
src/User/Tests/Entity/UserAttributeValueTest.php
src/User/Tests/Entity/UserRoleTest.php
src/User/Tests/Entity/UserSecondaryEmailTest.php
src/User/Tests/Entity/UserTest.php

clean up core entities

---

docs/ddd/collections.md
docs/ddd/factory/object.md
docs/ddd/identifiers.md
docs/ddd/identity-mapping.md
docs/ddd/repositories.md
docs/event-sourcing/domain-event-handlers.md
docs/event-sourcing/domain-events.md
docs/index.md
mkdocs.yml
src/Domain/Entity/Features/CanBeConfirmed.php
src/Domain/Entity/Features/CanBeEnabled.php
src/Domain/Event/ConfirmDomainEvent.php
src/Domain/Event/DisableDomainEvent.php
src/Domain/Event/DomainEventHandlerInterface.php
src/Domain/Event/DomainEventHandlerTrait.php
src/Domain/Event/DomainEventInterface.php
src/Domain/Event/EnableDomainEvent.php
src/Domain/Exception/UnknownDomainEventException.php

different approach for #50, to go before #49

setup basic event sourcing

---

docs/event-sourcing/domain-event-handlers.md
src/Domain/Entity/Features/CanBeConfirmed.php
src/Domain/Entity/Features/CanBeEnabled.php
src/Domain/Event/DomainEventHandlerInterface.php
src/Domain/Event/DomainEventHandlerTrait.php

update event handler return value

---

src/Domain/Infra/Doctrine/DomainEntityRepositoryTrait.php
src/Domain/Infra/Doctrine/DomainIdType.php
src/User/Infra/Doctrine/Repository/UserAttributeValueRepository.php

Fix incorrect parameter casting for e.g. binary uuid
Might also fix https://github.com/msgphp/symfony-demo-app/issues/8 for being the same root issue.

fix field criteria on binary uuid type

---

bin/phpunit-package
composer.json
src/Domain/Infra/Console/ContextBuilder/ClassContextBuilder.php
src/User/Command/ConfirmUserCommand.php
src/User/Command/Handler/ConfirmUserHandler.php
src/User/Event/UserConfirmedEvent.php
src/User/Infra/Console/Command/ConfirmUserCommand.php
src/UserBundle/DependencyInjection/Configuration.php
src/UserBundle/DependencyInjection/Extension.php

confirm user CLI command

---

src/User/Command/Handler/RequestUserPasswordHandler.php
src/User/Command/RequestUserPasswordCommand.php
src/User/Entity/Features/ResettablePassword.php
src/User/Event/Domain/RequestPasswordEvent.php
src/User/Event/UserPasswordRequestedEvent.php
src/UserBundle/DependencyInjection/Configuration.php
src/UserBundle/DependencyInjection/Extension.php

added request password command

---

docs/ddd/factory/entity-aware.md
phpstan.neon
src/Domain/Factory/EntityAwareFactory.php
src/Domain/Factory/EntityAwareFactoryInterface.php
src/Domain/Factory/EntityReferenceLoader.php
src/Domain/Infra/DependencyInjection/Bundle/BundleHelper.php
src/Domain/Infra/DependencyInjection/Bundle/ContainerHelper.php
src/Domain/Infra/DependencyInjection/Compiler/ResolveDomainPass.php
src/Domain/Infra/Doctrine/EntityReferenceLoader.php
src/Domain/Tests/Factory/EntityAwareFactoryTest.php
src/Domain/Tests/Factory/EntityReferenceLoaderTest.php
src/Domain/Tests/Fixtures/DoctrineDomainIdType.php
src/Domain/Tests/Infra/Doctrine/DomainEntityRepositoryTraitTest.php
src/Domain/Tests/Infra/Doctrine/EntityManagerTrait.php
src/Domain/Tests/Infra/Doctrine/EntityReferenceLoaderTest.php
src/Domain/composer.json
src/EavBundle/DependencyInjection/Extension.php
src/User/Infra/Doctrine/Repository/UsernameRepository.php
src/User/Repository/UsernameRepositoryInterface.php
src/UserBundle/DependencyInjection/Extension.php

 added EntityAwareFactory::reference()

---

src/Domain/Infra/Doctrine/DomainIdentityMapping.php
src/Domain/Tests/Infra/Doctrine/DomainIdentityMappingTest.php
src/Domain/Tests/Infra/InMemory/DomainIdentityMappingTest.php

fix doctrine identity mapping

---

docs/ddd/identities.md
docs/ddd/identity-mapping.md
src/Domain/DomainIdentityHelper.php
src/Domain/DomainIdentityMappingInterface.php
src/Domain/Infra/Doctrine/DomainIdentityMapping.php
src/Domain/Infra/InMemory/DomainEntityRepositoryTrait.php
src/Domain/Infra/InMemory/DomainIdentityMapping.php
src/Domain/Tests/DomainIdentityHelperTest.php
src/Domain/Tests/Infra/Doctrine/DomainIdentityMappingTest.php
src/Domain/Tests/Infra/InMemory/DomainIdentityMappingTest.php

favor null in case of no identity

---

src/Domain/Infra/DependencyInjection/Bundle/ContainerHelper.php
src/Domain/Infra/Doctrine/DomainEntityRepositoryTrait.php
src/Domain/Tests/Infra/Doctrine/DomainEntityRepositoryTraitTest.php

reproducible builds

---

src/Domain/Infra/DependencyInjection/Bundle/ConfigHelper.php
src/EavBundle/DependencyInjection/Configuration.php
src/UserBundle/DependencyInjection/Configuration.php

validate bundle class mapping

---

.codecov.yml
src/Domain/Infra/InMemory/DomainEntityRepositoryTrait.php
src/Domain/Tests/AbstractDomainEntityRepositoryTraitTest.php
src/Domain/Tests/Factory/DomainObjectFactoryTest.php
src/Domain/Tests/Infra/Doctrine/EntityFieldsMappingTest.php
src/Eav/Infra/Doctrine/EntityFieldsMapping.php
src/Eav/Tests/Infra/Doctrine/EntityFieldsMappingTest.php
src/User/Infra/Doctrine/EntityFieldsMapping.php
src/User/Tests/Infra/Doctrine/EntityFieldsMappingTest.php

add missing tests

---

src/User/Infra/Doctrine/Event/UsernameListener.php
src/User/Infra/Doctrine/Repository/UsernameRepository.php
src/User/README.md
src/UserBundle/DependencyInjection/Configuration.php
src/UserBundle/DependencyInjection/Extension.php
src/UserBundle/README.md

tweak Username entity

---

src/Domain/Infra/DependencyInjection/BundleHelper.php
src/Domain/Infra/DependencyInjection/Compiler/DoctrineObjectFieldMappingPass.php
src/Domain/Infra/DependencyInjection/Compiler/ResolveDomainPass.php
src/Domain/Infra/DependencyInjection/ConfigHelper.php
src/Domain/Infra/DependencyInjection/ContainerHelper.php
src/EavBundle/DependencyInjection/Configuration.php
src/EavBundle/DependencyInjection/Extension.php
src/EavBundle/MsgPhpEavBundle.php
src/EavBundle/Resources/config/doctrine.php
src/UserBundle/DependencyInjection/Configuration.php
src/UserBundle/DependencyInjection/Extension.php
src/UserBundle/MsgPhpUserBundle.php
src/UserBundle/Resources/config/doctrine.php
src/UserBundle/Resources/config/message.php

 drop DI/Bundle ns + resolve mapped id classes

---

UPGRADE-0.2.md
phpstan.neon
src/Domain/Infra/Config/ClassMappingNode.php
src/Domain/Infra/Config/ClassMappingNodeDefinition.php
src/Domain/Infra/Config/NodeBuilder.php
src/Domain/Infra/Config/TreeBuilder.php
src/Domain/Infra/DependencyInjection/BundleHelper.php
src/Domain/Infra/DependencyInjection/ConfigHelper.php
src/Domain/Infra/DependencyInjection/ContainerHelper.php
src/EavBundle/DependencyInjection/Configuration.php
src/EavBundle/DependencyInjection/Extension.php
src/User/Entity/Credential/Anonymous.php
src/UserBundle/DependencyInjection/Configuration.php
src/UserBundle/DependencyInjection/Extension.php

[0.2] revise bundle config

---

src/Domain/Infra/DependencyInjection/Compiler/ResolveDomainPass.php
src/Domain/Infra/DependencyInjection/ContainerHelper.php
src/Domain/Infra/Doctrine/DomainIdentityMapping.php
src/Domain/Tests/Infra/Doctrine/DomainIdentityMappingTest.php

 tweak class mapping usage

---

UPGRADE-0.2.md
src/User/Infra/Security/UserParamConverter.php
src/UserBundle/Resources/config/security.php

[0.2] name user param converter

---

src/Domain/Infra/Doctrine/EntityAwareFactory.php
src/Domain/Tests/Infra/Doctrine/EntityAwareFactoryTest.php

fix doctrine entity factory

---

src/Domain/Infra/DependencyInjection/ConfigHelper.php
src/User/Command/ConfirmUserEmailCommand.php
src/User/Command/Handler/ConfirmUserEmailHandler.php
src/User/Command/Handler/DeleteUserEmailHandler.php
src/User/Entity/UserEmail.php
src/User/Event/UserEmailConfirmedEvent.php
src/User/Infra/Doctrine/EntityFieldsMapping.php
src/User/Infra/Doctrine/Repository/UserEmailRepository.php
src/User/Infra/Doctrine/Resources/dist-mapping/User.Entity.UserEmail.orm.xml
src/User/Repository/UserEmailRepositoryInterface.php
src/User/Tests/Entity/UserEmailTest.php
src/UserBundle/DependencyInjection/Configuration.php

cleanup user email leftovers

---

src/Domain/Infra/Config/ClassMappingNodeDefinition.php
src/User/Entity/Fields/RoleField.php
src/User/Entity/Role.php
src/User/Entity/UserRole.php
src/User/Infra/Doctrine/EntityFieldsMapping.php
src/User/Infra/Doctrine/Repository/RoleRepository.php
src/User/Infra/Doctrine/Resources/dist-mapping/User.Entity.Role.orm.xml
src/User/Infra/Doctrine/Resources/dist-mapping/User.Entity.UserRole.orm.xml
src/User/Repository/RoleRepositoryInterface.php
src/User/Tests/Entity/Fields/RoleFieldTest.php
src/User/Tests/Entity/UserRoleTest.php
src/UserBundle/DependencyInjection/Configuration.php
src/UserBundle/DependencyInjection/Extension.php

add first class Role entity

---

src/User/Command/AddUserEmailCommand.php
src/User/Command/Handler/AddUserEmailHandler.php
src/User/Entity/Fields/EmailsField.php
src/User/Event/UserEmailAddedEvent.php
src/UserBundle/DependencyInjection/Configuration.php
src/UserBundle/DependencyInjection/Extension.php

update emails terminology

---

src/Domain/Infra/Console/ContextBuilder/ClassContextBuilder.php
src/Domain/Infra/Console/ContextBuilder/ContextBuilderInterface.php
src/Domain/Infra/DependencyInjection/BundleHelper.php
src/Domain/Infra/DependencyInjection/Compiler/ResolveDomainPass.php
src/EavBundle/DependencyInjection/Configuration.php
src/User/Command/AddUserRoleCommand.php
src/User/Command/DeleteUserRoleCommand.php
src/User/Command/Handler/AddUserRoleHandler.php
src/User/Command/Handler/DeleteUserRoleHandler.php
src/User/Entity/Fields/RolesField.php
src/User/Event/UserRoleAddedEvent.php
src/User/Event/UserRoleDeletedEvent.php
src/User/Infra/Console/Command/AddUserRoleCommand.php
src/User/Infra/Console/Command/ChangeUserCredentialCommand.php
src/User/Infra/Console/Command/DeleteUserRoleCommand.php
src/User/Infra/Console/Command/UserCommand.php
src/User/Infra/Console/Command/UserRoleCommand.php
src/User/Infra/Doctrine/EntityFieldsMapping.php
src/User/Infra/Doctrine/Repository/UserRoleRepository.php
src/User/Infra/Validator/ExistingUsername.php
src/User/Infra/Validator/UniqueUsername.php
src/User/Repository/UserRoleRepositoryInterface.php
src/UserBundle/DependencyInjection/Configuration.php
src/UserBundle/DependencyInjection/Extension.php
src/UserBundle/Resources/config/console.php

added RolesField

---

src/User/Command/AddUserAttributeValueCommand.php
src/User/Command/ChangeUserAttributeValueCommand.php
src/User/Command/DeleteUserAttributeValueCommand.php
src/User/Command/Handler/AddUserAttributeValueHandler.php
src/User/Command/Handler/ChangeUserAttributeValueHandler.php
src/User/Command/Handler/DeleteUserAttributeValueHandler.php
src/User/Event/UserAttributeValueAddedEvent.php
src/User/Event/UserAttributeValueChangedEvent.php
src/User/Event/UserAttributeValueDeletedEvent.php
src/User/Infra/Doctrine/Repository/UserAttributeValueRepository.php
src/User/Infra/Doctrine/Resources/dist-mapping/User.Entity.UserAttributeValue.orm.xml
src/User/Repository/UserAttributeValueRepositoryInterface.php

added user attributes domain infra

---

src/Eav/Entity/Fields/AttributesField.php
src/Eav/Tests/Entity/Fields/AttributeValueFieldTest.php
src/Eav/Tests/Entity/Fields/AttributesFieldTest.php
src/Eav/Tests/Infra/Doctrine/EntityFieldsMappingTest.php
src/User/Entity/Fields/AttributeValuesField.php
src/User/Infra/Doctrine/EntityFieldsMapping.php
src/User/Tests/Entity/Fields/AttributeValuesFieldTest.php
src/User/Tests/Entity/Fields/EmailsFieldTest.php
src/User/Tests/Entity/Fields/RoleFieldTest.php
src/User/Tests/Entity/Fields/UserFieldTest.php

added user attribute values field

---

docs/cookbook/bundle-installation.md
docs/index.md
mkdocs.yml
src/EavBundle/DependencyInjection/Configuration.php

bundle installation cookbook

---

docs/ddd/factory/entity-aware.md
docs/projection/documents.md
src/Domain/Projection/DomainProjectionDocument.php

 tweak ProjectionDocument

---

src/Domain/Infra/DependencyInjection/ContainerHelper.php
src/UserBundle/DependencyInjection/Configuration.php
src/UserBundle/DependencyInjection/Extension.php

fixes https://github.com/msgphp/symfony-demo-app/issues/32
cc @crabnky my bad :)

fix class mapping config

---

bin/smoke-test-bundles
src/UserBundle/DependencyInjection/Extension.php

- wait for recipes
- removed unused xml mappings from cache

validate ORM schema

---

.travis.yml
bin/create-project
bin/phpunit-package
bin/smoke-test-bundles

tweak build

---

UPGRADE-0.3.md
src/Eav/Tests/Entity/Fields/AttributesFieldTest.php
src/User/Tests/Entity/Fields/EmailsFieldTest.php
src/User/Tests/Entity/Fields/RolesFieldTest.php
src/User/Tests/Infra/Security/SecurityUserProviderTest.php
src/UserBundle/Maker/UserMaker.php
src/UserBundle/Resources/skeleton/config.php
src/UserBundle/Resources/skeleton/controller/ForgotPasswordController.php
src/UserBundle/Resources/skeleton/controller/ResetPasswordController.php
src/UserBundle/Resources/skeleton/service/UserRolesProvider.php

enable user roles inverse side in make:user

---

.travis.yml

fixes cross testing packages, reduces jobs
cc @GawainLynch

tweak travis

---

bin/build-docrefs
composer.json
docs/.refs/available-bundles.php
docs/.refs/doctrine-identifier-types.php
docs/cookbook/bundle-installation.md
docs/reference/doctrine-identifier-types.md
src/EavBundle/composer.json
src/UserBundle/composer.json

automate doc references

---

src/Domain/Infra/DependencyInjection/BundleHelper.php
src/Domain/Infra/DependencyInjection/Compiler/ResolveDomainPass.php
src/Domain/Infra/DependencyInjection/ContainerHelper.php
src/EavBundle/DependencyInjection/Extension.php
src/EavBundle/MsgPhpEavBundle.php
src/EavBundle/Resources/config/doctrine.php
src/UserBundle/DependencyInjection/Extension.php
src/UserBundle/MsgPhpUserBundle.php
src/UserBundle/Resources/config/doctrine.php

Tweak Doctrine ORM wiring

---

src/Domain/Infra/DependencyInjection/Compiler/ResolveDomainPass.php
src/Domain/Infra/DependencyInjection/ContainerHelper.php
src/EavBundle/DependencyInjection/Extension.php
src/UserBundle/DependencyInjection/Extension.php

tweak wiring

---

UPGRADE-0.4.md
src/UserBundle/DependencyInjection/Extension.php
src/UserBundle/Resources/config/twig.php
src/UserBundle/Twig/GlobalVariable.php

improve twig variables

---

src/User/Entity/Credential/EmailSaltedPassword.php
src/User/Entity/Credential/NicknameSaltedPassword.php
src/UserBundle/Maker/UserMaker.php
src/UserBundle/Resources/skeleton/security.php

handle password salt in make:user

---

UPGRADE-0.5.md
docs/infrastructure/api-platform.md
docs/infrastructure/elasticsearch.md
docs/infrastructure/symfony-console.md
docs/projection/document-transformers.md
docs/projection/documents.md
docs/projection/models.md
docs/projection/repositories.md
docs/projection/synchronization.md
docs/projection/type-registry.md
src/Domain/Command/Handler/DeleteProjectionDocumentHandler.php
src/Domain/Command/Handler/SaveProjectionDocumentHandler.php
src/Domain/Infra/ApiPlatform/ProjectionDataProvider.php
src/Domain/Infra/Console/Command/InitializeProjectionTypesCommand.php
src/Domain/Infra/Console/Command/SynchronizeProjectionsCommand.php
src/Domain/Infra/Elasticsearch/ProjectionRepository.php
src/Domain/Infra/Elasticsearch/ProjectionTypeRegistry.php
src/Domain/Projection/ProjectionDocument.php
src/Domain/Projection/ProjectionDocumentProvider.php
src/Domain/Projection/ProjectionDocumentTransformerInterface.php
src/Domain/Projection/ProjectionInterface.php
src/Domain/Projection/ProjectionRepositoryInterface.php
src/Domain/Projection/ProjectionSynchronization.php
src/Domain/Projection/ProjectionTypeRegistryInterface.php

rename projection package classes

---

phpstan.neon
src/User/Infra/Security/Jwt/SecurityUserProvider.php
src/User/composer.json
src/UserBundle/Resources/config/security.php
src/UserBundle/composer.json

fixes https://github.com/msgphp/symfony-demo-app/issues/41, #164

update lexik/jwt-authentication-bundle to 2.5@stable

---

docs/reference/messages.md
src/User/Command/CreateRoleCommand.php
src/User/Command/DeleteRoleCommand.php
src/User/Command/Handler/CreateRoleHandler.php
src/User/Command/Handler/DeleteRoleHandler.php
src/User/Event/RoleCreatedEvent.php
src/User/Event/RoleDeletedEvent.php
src/User/Infra/Console/Command/CreateRoleCommand.php
src/User/Infra/Console/Command/DeleteRoleCommand.php
src/User/Infra/Console/Command/RoleAwareTrait.php
src/User/Infra/Console/Command/RoleCommand.php
src/User/Infra/Console/Command/UserRoleCommand.php
src/UserBundle/DependencyInjection/Compiler/CleanupPass.php
src/UserBundle/DependencyInjection/Configuration.php
src/UserBundle/DependencyInjection/Extension.php

add role commands

---

src/User/Infra/Validator/ExistingUsername.php
src/User/Infra/Validator/UniqueUsername.php

Add constraint error names

---

UPGRADE-0.6.md
docs/ddd/collections.md
src/Domain/Infra/ApiPlatform/Paginator.php
src/Domain/Infra/ApiPlatform/ProjectionDataProvider.php
src/Domain/Infra/Elasticsearch/ProjectionRepository.php
src/Domain/PaginatedDomainCollection.php
src/Domain/PaginatedDomainCollectionInterface.php
src/Domain/Projection/ProjectionRepositoryInterface.php
src/Domain/Tests/PaginatedDomainCollectionTest.php

ref https://github.com/msgphp/symfony-demo-app/issues/31

api pagination

---

UPGRADE-0.6.md
docs/ddd/collections.md
docs/ddd/factory/static.md
docs/ddd/identifiers.md
docs/ddd/identity-mapping.md
docs/ddd/repositories.md
src/Domain/Factory/DomainCollectionFactory.php
src/Domain/Tests/Factory/DomainCollectionFactoryTest.php

add DomainCollectionFactory::createFromCallable

---

UPGRADE-0.6.md
src/UserBundle/DependencyInjection/Configuration.php

default mapped_by to null for username lookups

---

src/User/Infra/Doctrine/Resources/dist-mapping/User.Entity.UserAttributeValue.orm.xml

eagerly fetch attribute values

---

.travis.yml
bin/phpunit-package

update phpunit to 7.3

---

composer.json
src/Domain/Infra/DependencyInjection/BundleHelper.php
src/Domain/composer.json

inject entity aware factory by default

---

UPGRADE-0.7.md
bin/compile-docrefs
docs/.refs/entities.php
src/Eav/composer.json
src/EavBundle/composer.json
src/User/Entity/Username.php
src/User/Infra/Console/Command/SynchronizeUsernamesCommand.php
src/User/Infra/Doctrine/Event/UsernameListener.php
src/User/Infra/Doctrine/Repository/UserRepository.php
src/User/Infra/Doctrine/Repository/UsernameRepository.php
src/User/Infra/Doctrine/Resources/dist-mapping/User.Entity.Username.orm.xml
src/User/composer.json
src/UserBundle/DependencyInjection/Configuration.php
src/UserBundle/DependencyInjection/Extension.php
src/UserBundle/composer.json

revise username entity

---

src/User/Infra/Security/SecurityUser.php
src/User/Infra/Security/SecurityUserProvider.php
src/User/Tests/Infra/Security/SecurityUserProviderTest.php
src/User/Tests/Infra/Security/SecurityUserTest.php

ref https://github.com/msgphp/symfony-demo-app/issues/67

add SecurityUser::getOriginUsername

---

bin/sa
phpstan.neon
src/Domain/DomainCollection.php
src/Domain/DomainId.php
src/Domain/Infra/Doctrine/DomainCollection.php
src/Domain/Infra/Uuid/DomainId.php
src/Domain/PaginatedDomainCollection.php
tests/fixtures/sa/return-static.php

fix SA on return self

---

.php_cs.dist
bin/cs
bin/sami
composer.json

update to php-cs-fixer.phar

---

docs/ddd/collections.md
src/Domain/DomainCollection.php
src/Domain/Exception/EmptyCollectionException.php
src/Domain/Exception/UnknownCollectionElementException.php
src/Domain/Infra/Doctrine/DomainCollection.php
src/Domain/Infra/InMemory/DomainEntityRepositoryTrait.php
src/Domain/Tests/AbstractDomainCollectionTest.php
src/Domain/Tests/DomainCollectionTest.php

revise collection api

---

src/Domain/Infra/Config/ClassMappingNode.php
src/Domain/Infra/Config/ClassMappingNodeDefinition.php
src/Domain/Infra/DependencyInjection/FeatureDetection.php
src/EavBundle/DependencyInjection/Configuration.php
src/EavBundle/DependencyInjection/Extension.php
src/EavBundle/Resources/config/doctrine.php
src/EavBundle/Resources/config/message.php
src/UserBundle/DependencyInjection/Configuration.php
src/UserBundle/DependencyInjection/Extension.php
src/UserBundle/Maker/UserMaker.php
src/UserBundle/Resources/config/console.php
src/UserBundle/Resources/config/doctrine.php
src/UserBundle/Resources/config/message.php

enable user-eav in bundle

---

src/User/Infra/Form/Type/HashedPasswordType.php
src/User/Infra/Security/PasswordHashing.php
src/User/Password/PasswordHashing.php
src/User/Tests/Infra/Form/Type/HashedPasswordTypeTest.php
src/User/composer.json

remove plain password from memory

---

src/User/Infra/Console/Command/AddUserRoleCommand.php
src/User/Infra/Console/Command/DeleteUserRoleCommand.php
src/User/Infra/Console/Command/RoleAwareTrait.php

auto create role during user:role:add

---

bin/lint

add linter

---

docs/infrastructure/doctrine-orm.md
src/Domain/Infra/Doctrine/DomainEntityRepositoryTrait.php
src/Domain/Tests/Infra/Doctrine/DomainEntityRepositoryTraitTest.php
src/Eav/Infra/Doctrine/Repository/AttributeRepository.php
src/Eav/Infra/Doctrine/Repository/EntityAttributeValueRepositoryTrait.php
src/User/Infra/Doctrine/Repository/RoleRepository.php
src/User/Infra/Doctrine/Repository/UserEmailRepository.php
src/User/Infra/Doctrine/Repository/UserRepository.php
src/User/Infra/Doctrine/Repository/UserRoleRepository.php
src/User/Infra/Doctrine/Repository/UsernameRepository.php
src/UserEav/Infra/Doctrine/Repository/UserAttributeValueRepository.php

auto-detect entity-alias in doctrine repository

---

docs/ddd/identity-helper.md
docs/ddd/identity-mapping.md
src/Domain/DomainIdentityHelper.php
src/Domain/DomainIdentityMappingInterface.php
src/Domain/Exception/DuplicateEntityException.php
src/Domain/Exception/EntityNotFoundException.php
src/Domain/Infra/Doctrine/DomainEntityRepositoryTrait.php
src/Domain/Infra/Doctrine/DomainIdentityMapping.php
src/Domain/Infra/InMemory/DomainEntityRepositoryTrait.php
src/Domain/Infra/InMemory/DomainIdentityMapping.php
src/Domain/Tests/AbstractDomainIdentityMappingTest.php
src/Domain/Tests/DomainIdentityHelperTest.php

cleanup DomainIdentityHelper/Mapping

---

src/Domain/Factory/EntityAwareFactory.php
src/Domain/Tests/Factory/EntityAwareFactoryTest.php

re-identity DomainIdInterface in EntityAwareFactory::identify()

---

src/Domain/Factory/DomainObjectFactory.php
src/Domain/Infra/Console/Context/ClassContextFactory.php
src/Domain/Infra/DependencyInjection/BundleHelper.php
src/Domain/Infra/DependencyInjection/PackageMetadata.php
src/Domain/Tests/Infra/Doctrine/ObjectMappingsTest.php
src/Eav/Tests/Infra/Doctrine/ObjectMappingsTest.php
src/EavBundle/DependencyInjection/Configuration.php
src/EavBundle/DependencyInjection/Extension.php
src/EavBundle/Resources/config/doctrine.php
src/EavBundle/Resources/config/message.php
src/User/Tests/Infra/Doctrine/ObjectMappingsTest.php
src/UserBundle/DependencyInjection/Configuration.php
src/UserBundle/DependencyInjection/Extension.php
src/UserBundle/Maker/UserMaker.php
src/UserBundle/Resources/config/console.php
src/UserBundle/Resources/config/doctrine.php
src/UserBundle/Resources/config/message.php
src/UserEav/Tests/Infra/Doctrine/EavObjectMappingsTest.php

Drop GLOB_BRACE dependency

---

docs/ddd/factory/entity-aware.md
src/Domain/Factory/EntityAwareFactory.php
src/Domain/Infra/DependencyInjection/BundleHelper.php
src/Domain/Infra/DependencyInjection/ExtensionHelper.php
src/Domain/Tests/Factory/EntityAwareFactoryTest.php
src/EavBundle/DependencyInjection/Configuration.php
src/EavBundle/DependencyInjection/Extension.php
src/User/Command/Handler/AddUserEmailHandler.php
src/User/Command/Handler/AddUserRoleHandler.php
src/UserBundle/DependencyInjection/Configuration.php
src/UserBundle/DependencyInjection/Extension.php

Remove entity to identifier mapping

---

docs/ddd/factory/entity-aware.md
src/Domain/Factory/EntityAwareFactory.php
src/Domain/Factory/EntityAwareFactoryInterface.php
src/Domain/Infra/Doctrine/EntityAwareFactory.php
src/Domain/Tests/Factory/EntityAwareFactoryTest.php
src/Domain/Tests/Infra/Doctrine/EntityAwareFactoryTest.php
src/Eav/Command/Handler/CreateAttributeHandler.php
src/User/Command/Handler/CreateUserHandler.php
src/UserEav/Command/Handler/AddUserAttributeValueHandler.php

Remove EntityAwareFactoryInterface::nextIdentifier()

---

docs/ddd/factory/entity-aware.md
src/Domain/Factory/EntityAwareFactory.php
src/Domain/Factory/EntityAwareFactoryInterface.php
src/Domain/Infra/Doctrine/EntityAwareFactory.php
src/Domain/Tests/Factory/EntityAwareFactoryTest.php
src/Domain/Tests/Infra/Doctrine/EntityAwareFactoryTest.php
src/User/Infra/Console/Command/UserCommand.php
src/User/Infra/Security/Jwt/SecurityUserProvider.php

Remove EntityAwareFactoryInterface::identify()

---

src/Eav/Command/Handler/CreateAttributeHandler.php
src/Eav/Event/AttributeCreatedEvent.php
src/User/Command/Handler/AddUserEmailHandler.php
src/User/Command/Handler/AddUserRoleHandler.php
src/User/Command/Handler/CreateRoleHandler.php
src/User/Command/Handler/CreateUserHandler.php
src/User/Event/RoleCreatedEvent.php
src/User/Event/UserCreatedEvent.php
src/User/Event/UserEmailAddedEvent.php
src/User/Event/UserRoleAddedEvent.php
src/UserEav/Command/Handler/AddUserAttributeValueHandler.php
src/UserEav/Event/UserAttributeValueAddedEvent.php

Pass context along event messages

---

docs/ddd/identifiers.md
src/Domain/DomainId.php
src/Domain/DomainIdInterface.php
src/Domain/Infra/Uuid/DomainId.php
src/Domain/Tests/AbstractDomainEntityRepositoryTraitTest.php
src/User/Infra/Security/SecurityUser.php

cleanup serialization

---

src/User/Infra/Console/Command/SynchronizeUsernamesCommand.php
src/User/Infra/Doctrine/Event/UsernameListener.php
src/User/Infra/Doctrine/Repository/UserRepository.php
src/User/Infra/Doctrine/Repository/UsernameRepository.php
src/User/Infra/Doctrine/UsernameLookup.php
src/User/Repository/UsernameRepositoryInterface.php
src/UserBundle/DependencyInjection/Extension.php
src/UserBundle/Resources/config/doctrine.php

fix username syncing (removes UsernameRepositoryInterface::findAllFromTargets())

---

src/Domain/DomainId.php
src/Domain/Tests/DomainIdTest.php

disallow empty string ID values

---

src/Eav/ScalarAttributeId.php
src/Eav/ScalarAttributeValueId.php
src/Eav/Tests/Command/IntegrationTestTrait.php
src/Eav/Tests/Fixtures/Entities/TestAttribute.php
src/EavBundle/DependencyInjection/Configuration.php
src/User/ScalarUserId.php
src/User/Tests/Command/Handler/CreateUserHandlerTest.php
src/User/Tests/Infra/Security/SecurityUserTest.php
src/UserBundle/DependencyInjection/Configuration.php

Rename <Entity>Id to Scalar<Entity>Id

---

src/Eav/Infra/Uuid/AttributeUuid.php
src/Eav/Infra/Uuid/AttributeValueUuid.php
src/EavBundle/DependencyInjection/Configuration.php
src/User/Infra/Uuid/UserUuid.php
src/UserBundle/DependencyInjection/Configuration.php

Rename Infra\Uuid\<Entity>Id to <Entity>Uuid

---

docs/ddd/identifiers.md
docs/event-sourcing/event-handlers.md
docs/event-sourcing/events.md
docs/infrastructure/doctrine-dbal.md
docs/infrastructure/doctrine-orm.md
docs/infrastructure/elasticsearch.md
docs/infrastructure/uuid.md
docs/message-driven/cqrs.md
docs/projection/document-transformers.md
docs/projection/documents.md
docs/projection/repositories.md
docs/projection/synchronization.md
src/Domain/Infra/Doctrine/DomainIdType.php
src/Domain/Tests/Fixtures/Entities/TestCompositeEntity.php
src/Domain/Tests/Fixtures/Entities/TestEntity.php
src/Domain/Tests/Fixtures/Entities/TestPrimitiveEntity.php
src/Domain/Tests/Fixtures/TestDomainIdType.php
src/Domain/Tests/Fixtures/TestOtherDomainIdType.php
src/Domain/Tests/Infra/Doctrine/DomainEntityRepositoryTraitTest.php
src/Domain/Tests/Infra/Doctrine/DomainIdTypeTest.php
src/Domain/Tests/Infra/Doctrine/EntityManagerTestTrait.php

mark Infra\Doctrine\DomainIdType an abstract

---

src/Domain/Projection/Command/DeleteProjectionDocumentCommand.php
src/Domain/Projection/Command/Handler/DeleteProjectionDocumentHandler.php
src/Domain/Projection/Command/Handler/SaveProjectionDocumentHandler.php
src/Domain/Projection/Command/SaveProjectionDocumentCommand.php

Rename Command\*Projection* to Projection\Command\

---

src/Domain/Projection/Command/Handler/DeleteProjectionDocumentHandler.php
src/Domain/Projection/Command/Handler/SaveProjectionDocumentHandler.php
src/Domain/Projection/Event/ProjectionDocumentDeletedEvent.php
src/Domain/Projection/Event/ProjectionDocumentSavedEvent.php

Rename Event\*Projection* to Projection\Event\

---

docs/ddd/object-factory.md
src/Domain/Factory/GenericDomainObjectFactory.php
src/Domain/Infra/DependencyInjection/BundleHelper.php
src/Domain/Tests/Factory/GenericDomainObjectFactoryTest.php
src/Eav/Tests/Command/IntegrationTestTrait.php
src/User/Tests/Command/Handler/CreateUserHandlerTest.php

Rename DomainObjectFactory to GenericDomainObjectFactory

---

src/User/Entity/Credential/Email.php
src/User/Entity/Credential/EmailPassword.php
src/User/Entity/Credential/Features/EmailAsUsername.php
src/User/Entity/Credential/Features/NicknameAsUsername.php
src/User/Entity/Credential/Features/PasswordProtected.php
src/User/Entity/Credential/Nickname.php
src/User/Entity/Credential/NicknamePassword.php
src/User/Entity/Credential/Token.php
src/User/Entity/Features/AbstractCredential.php
src/User/Entity/Features/AbstractPasswordCredential.php
src/User/Entity/Features/EmailCredential.php
src/User/Entity/Features/NicknameCredential.php
src/User/Entity/Features/TokenCredential.php
src/User/Event/Domain/ChangeCredentialEvent.php

Revise user credentials

---

phpstan.neon
src/Domain/GenericDomainCollection.php
src/Domain/Infra/Doctrine/DomainEntityRepositoryTrait.php
src/Domain/PaginatedDomainCollection.php
src/Domain/Tests/Factory/GenericDomainObjectFactoryTest.php
src/Domain/Tests/GenericDomainCollectionTest.php
src/User/Entity/Fields/EmailsField.php
src/User/Entity/Fields/RolesField.php
src/User/Infra/Doctrine/Repository/UsernameRepository.php
src/User/Tests/Role/UserRoleProviderTest.php
src/UserEav/Entity/Fields/AttributeValuesField.php

Renamed DomainCollection to GenericDomainCollection

---

src/Domain/GenericPaginatedDomainCollection.php
src/Domain/Infra/ApiPlatform/ProjectionDataProvider.php
src/Domain/Infra/Elasticsearch/ProjectionRepository.php
src/Domain/Tests/GenericPaginatedDomainCollectionTest.php

Renamed PaginatedDomainCollection to GenericPaginatedDomainCollection

---

src/User/Infra/Security/SecurityUser.php
src/User/Tests/Infra/Security/SecurityUserProviderTest.php
src/User/Tests/Infra/Security/SecurityUserTest.php

add SecurityUser::getPasswordAlgorithm()

---

src/User/Password/GenericPasswordHashing.php
src/User/Tests/Password/GenericPasswordHashingTest.php
src/UserBundle/Resources/config/services.php

Renamed PasswordHashing to GenericPasswordHashing

---

src/User/Infra/Security/PasswordHashing.php
src/User/Infra/Security/SecurityUserHashingFactory.php
src/UserBundle/Resources/config/security.php

add SecurityUserHashingFactory

---

src/User/Infra/Form/Type/HashedPasswordType.php
src/User/Tests/Infra/Form/Type/HashedPasswordTypeTest.php

Alternative is using `password_options.constraints`

Removed option "password_confirm_current" + default "inherit_data" in HashedPasswordType

---

src/Domain/Infrastructure/DependencyInjection/Compiler/ResolveDomainPass.php
src/User/Infrastructure/Doctrine/Event/UsernameListener.php
src/UserBundle/DependencyInjection/Extension.php
src/UserBundle/Resources/config/doctrine.php

Drop support for MsgPhp\ entity class reference in username_lookup

---

src/User/Infrastructure/Form/Extension/UserExtension.php
src/User/Tests/Infrastructure/Form/Extension/UserExtensionTest.php
src/UserBundle/Resources/config/form.php
src/UserBundle/Resources/skeleton/controller/ForgotPasswordController.php
src/UserBundle/Resources/skeleton/form/ForgotPasswordType.php

Add form UserExtension

---

docs/event-sourcing/event-handlers.md
docs/event-sourcing/events.md
src/Domain/Event/DomainEventHandlerTrait.php
src/Domain/Model/CanBeConfirmed.php
src/Domain/Model/CanBeEnabled.php
src/Domain/Tests/Event/DomainEventHandlerTraitTest.php
src/Domain/Tests/Model/CanBeConfirmedTest.php
src/Domain/Tests/Model/CanBeEnabledTest.php
src/User/Model/AbstractCredential.php
src/User/Model/ResettablePassword.php

Use "on...Event()" method convention in DomainEventHandlerTrait

---

psalm.xml
src/User/Command/CancelUserPasswordRequest.php
src/User/Command/Handler/CancelUserPasswordRequestHandler.php
src/User/Event/Domain/CancelPasswordRequest.php
src/User/Event/UserPasswordRequestCanceled.php
src/User/Model/ResettablePassword.php

Add CancelUserPasswordRequest command

---

docs/message-driven/cqrs.md
phpstan.neon
psalm.xml
src/Domain/Event/EventSourcingCommandHandlerTrait.php
src/User/Command/Handler/CancelUserPasswordRequestHandler.php
src/User/Command/Handler/ChangeUserCredentialHandler.php
src/User/Command/Handler/ConfirmUserEmailHandler.php
src/User/Command/Handler/ConfirmUserHandler.php
src/User/Command/Handler/DisableUserHandler.php
src/User/Command/Handler/EnableUserHandler.php
src/User/Command/Handler/RequestUserPasswordHandler.php
src/User/Event/UserCredentialChanged.php
src/User/Infrastructure/Console/Command/ChangeUserCredentialCommand.php

Rename EventSourcingCommandHandlerTrait::handle() to handleEvent()

---

src/User/Command/Handler/ResetUserPasswordHandler.php
src/User/Command/ResetUserPassword.php
src/User/Event/Domain/FinishPasswordRequest.php
src/User/Event/UserPasswordRequestFinished.php
src/User/Model/ResettablePassword.php
src/UserBundle/DependencyInjection/Compiler/CleanupPass.php
src/UserBundle/DependencyInjection/Configuration.php
src/UserBundle/Resources/skeleton/controller/ResetPasswordController.tpl.php

add ResetUserPassword command

---

src/User/Infrastructure/Security/DataCollector.php
src/User/Infrastructure/Security/HashingFactory.php
src/User/Infrastructure/Security/SecurityUserProvider.php
src/User/Infrastructure/Security/TokenStorageAwareTrait.php
src/User/Infrastructure/Security/UserIdentity.php
src/User/Tests/Infrastructure/Security/SecurityUserProviderTest.php
src/User/Tests/Infrastructure/Security/UserIdentityTest.php
src/UserBundle/Resources/config/security.php
src/UserBundle/Resources/skeleton/security.tpl.php
src/UserBundle/Twig/GlobalVariable.php

Rename SecurtiyUser to UserIdentity

---

src/UserBundle/Resources/skeleton/controller/ProfileController.tpl.php
src/UserBundle/Resources/skeleton/controller/ResetPasswordController.tpl.php

Generate default param converters

---

composer.json
phpstan.neon
psalm.xml
src/UserBundle/DependencyInjection/Configuration.php
src/UserBundle/Maker/UserMaker.php
src/UserBundle/Resources/skeleton/controller/ProfileController.tpl.php
src/UserBundle/Resources/skeleton/form/ChangePasswordType.tpl.php
src/UserBundle/Resources/skeleton/form/ChangeUsernameType.tpl.php
src/UserBundle/Resources/skeleton/template/profile.tpl.php
src/UserBundle/Resources/skeleton/template/register.tpl.php
src/UserBundle/Resources/skeleton/template/reset_password.tpl.php

generate change username/password forms

---

src/Eav/AttributeValue.php

renamed AttributeValue::prepareChecksumValue() to getIdentityValue()

[BC break] Revised AttributeValue checksum generation

---

src/UserBundle/Resources/skeleton/controller/ForgotPasswordController.tpl.php
src/UserBundle/Resources/skeleton/form/ForgotPasswordType.tpl.php

fixes #342
cc @dmagician this should do, a change is needed in your app

Prevent username guessing

---

src/Domain/Exception/DuplicateEntity.php
src/Domain/Exception/EmptyCollection.php
src/Domain/Exception/EntityNotFound.php
src/Domain/Exception/InvalidClass.php
src/Domain/Exception/UnknownCollectionElement.php
src/Domain/Factory/ClassMethodResolver.php
src/Domain/Factory/GenericDomainObjectFactory.php
src/Domain/GenericDomainCollection.php
src/Domain/Infrastructure/Console/Definition/DoctrineContextDefinition.php
src/Domain/Infrastructure/Doctrine/DomainCollection.php
src/Domain/Infrastructure/Doctrine/DomainEntityRepositoryTrait.php
src/Domain/Infrastructure/Doctrine/DomainObjectFactory.php
src/Domain/Tests/DomainCollectionTestCase.php
src/Domain/Tests/DomainEntityRepositoryTestCase.php
src/Domain/Tests/Factory/ClassMethodResolverTest.php
src/Domain/Tests/Factory/GenericDomainObjectFactoryTest.php
src/Domain/Tests/GenericDomainCollectionTest.php
src/Eav/Command/Handler/DeleteAttributeHandler.php
src/User/Command/Handler/DeleteRoleHandler.php
src/User/Command/Handler/DeleteUserEmailHandler.php
src/User/Command/Handler/DeleteUserHandler.php
src/User/Command/Handler/DeleteUserRoleHandler.php
src/User/Infrastructure/Console/Command/AddUserRoleCommand.php
src/User/Infrastructure/Form/Extension/UserExtension.php
src/User/Infrastructure/Security/DataCollector.php
src/User/Infrastructure/Security/Jwt/UserIdentityProvider.php
src/User/Infrastructure/Security/UserIdentityProvider.php
src/User/Tests/Infrastructure/Form/Extension/UserExtensionTest.php
src/User/Tests/Infrastructure/Security/UserIdentityProviderTest.php
src/UserEav/Command/Handler/DeleteUserAttributeValueHandler.php

Removed *Exception type suffix

---

src/UserBundle/Maker/UserMaker.php

Add make:user:msgphp --credential option

---

src/UserBundle/Maker/UserMaker.php

Flatten generated structure

---

src/UserBundle/Resources/skeleton/template/base.tpl.php
src/UserBundle/Resources/skeleton/template/profile.tpl.php
src/UserBundle/Resources/skeleton/translations/messages+intl-icu.en.xlf

Generate user menu

---

src/UserBundle/DependencyInjection/Configuration.php

deny overwriting msgphp_user.role_providers

---

docs/cookbook/configuring-doctrine-orm.md

Doctrine ORM installation document typo fix.

Update Doctrine ORM installation doc.

---

src/Domain/Infrastructure/Doctrine/DomainObjectMappings.php
src/Domain/Infrastructure/Doctrine/Event/ObjectMappingListener.php
src/Domain/Model/IntIdentity.php

add integer identity trait

---

docs/ddd/identifiers.md
src/Domain/DomainId.php
src/Domain/DomainIdTrait.php
src/Domain/Infrastructure/Uuid/DomainIdTrait.php
src/Domain/Tests/DomainIdTest.php
src/Domain/Tests/Infrastructure/Uuid/DomainIdTest.php

remove type hint from DomainId::equals()

---

docs/ddd/identifiers.md
docs/infrastructure/uuid.md
src/Domain/GenericDomainId.php
src/Domain/Infrastructure/Uuid/DomainUuid.php
src/Domain/Tests/Fixtures/CountableIterator.php
src/Domain/Tests/GenericDomainCollectionTest.php
src/Domain/Tests/GenericDomainIdTest.php
src/Domain/Tests/Infrastructure/Uuid/DomainUuidTest.php

add GenericDomainId + DomainUuid

---

docs/ddd/collections.md
docs/ddd/identifiers.md
src/Domain/AbstractDomainId.php
src/Domain/Tests/AbstractDomainIdTest.php

add AbstractDomainId in favor of DomainIdTrait
